### ISSUE TITLE
AdGuard访问上游1053失败

### ISSUE THREAD

**Issue by shihaoZheng** [DustinWin/dustinwin.github.io#48]
![image](https://github.com/user-attachments/assets/373fa3a4-f637-4106-bcb7-f9eab1582c45)
用的是Clash/分享篇/分享自己使用 ShellCrash 搭配 AdGuard Home 的一套配置.md
服务正常启动了，也能成功代理，但是发现AdGuard 那边测试上游失败了，好奇怪，大佬有排查的方向吗

**Comment by DustinWin** [comment]
AdGuard Home 安装时执行重定向命令了吗？

**Comment by shihaoZheng** [comment]
AdGuard 是以前就安装好的，
重定向命令指的是这些吗，我也重新安装执行安装了
/data/AdGuardHome/AdGuardHome -s install
/data/AdGuardHome/AdGuardHome -s start
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 5353
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5353
ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 5353
ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5353
这些有，就是把ShellCrash原来的内核换成了clash

**Comment by DustinWin** [comment]
`1053` 端口是不是被其它程序占用了？什么设备？

**Comment by shihaoZheng** [comment]
红米AX6000 
![image](https://github.com/user-attachments/assets/569e340e-3060-418f-ae58-04c18250c40c)

**Comment by shihaoZheng** [comment]
> > 红米AX6000 <img alt="image" width="54.150001525878906" height="21" src="https://private-user-images.githubusercontent.com/70837148/360975907-569e340e-3060-418f-ae58-04c18250c40c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjYyMDgsIm5iZiI6MTcyNDQyNTkwOCwicGF0aCI6Ii83MDgzNzE0OC8zNjA5NzU5MDctNTY5ZTM0MGUtMzA2MC00MThmLWFlNTgtMDRjMTgyNTBjNDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE1MTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZWY4NjRhNzg0NGVmMzkyYzMyZDJkZWZiM2NhOTdiMTNhMDc0ZDdkNGQzZTc0NWY4OGU2NzBkZTY0NjUzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rgZx71BwfM6dZlOVcSG9iYY9LOXFVZZy1XlTEvH0HD8">
> 
> 如果可以的话，建议恢复出厂设置，重新来一遍。
不行，恢复出厂设置，重新来一遍了，Clash/分享篇/分享自己使用 ShellCrash 搭配 AdGuard Home 的一套配置.md 装完代理，代理正常，再安装AdGuardHome还是一样出现这个问题

**Comment by DustinWin** [comment]
> > > 红米AX6000 <img alt="image" width="54.150001525878906" height="21" src="https://private-user-images.githubusercontent.com/70837148/360975907-569e340e-3060-418f-ae58-04c18250c40c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjYyMDgsIm5iZiI6MTcyNDQyNTkwOCwicGF0aCI6Ii83MDgzNzE0OC8zNjA5NzU5MDctNTY5ZTM0MGUtMzA2MC00MThmLWFlNTgtMDRjMTgyNTBjNDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE1MTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZWY4NjRhNzg0NGVmMzkyYzMyZDJkZWZiM2NhOTdiMTNhMDc0ZDdkNGQzZTc0NWY4OGU2NzBkZTY0NjUzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rgZx71BwfM6dZlOVcSG9iYY9LOXFVZZy1XlTEvH0HD8">
> > 
> > 
> > 如果可以的话，建议恢复出厂设置，重新来一遍。
> > 不行，恢复出厂设置，重新来一遍了，Clash/分享篇/分享自己使用 ShellCrash 搭配 AdGuard Home 的一套配置.md 装完代理，代理正常，再安装AdGuardHome还是一样出现这个问题

方便的话，通过 Email 联系我。

**Comment by shihaoZheng** [comment]
![image](https://github.com/user-attachments/assets/6744841d-5d78-4dcc-95a8-092487ec1d2e)
同时AdGuard无法更新和下载规则

**Comment by DustinWin** [comment]
> ![image](https://private-user-images.githubusercontent.com/70837148/361149829-6744841d-5d78-4dcc-95a8-092487ec1d2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MTMyMDYsIm5iZiI6MTcyNDUxMjkwNiwicGF0aCI6Ii83MDgzNzE0OC8zNjExNDk4MjktNjc0NDg0MWQtNWQ3OC00ZGNjLTk1YTgtMDkyNDg3ZWMxZDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDE1MjE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYzhhZTg0ZTgyZTQ3ZWU0Mzc0YTM5Mzk1ZjI1ZTE1MmNkZjhiMmRmNTNjODM3YzlmM2ZlMWZkOTczMWRhMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YnXngf-iaKUGoL8M5vRnuM-aX-iidTdteWtvTFZiB_4) 同时AdGuard无法更新和下载规则

你这问题我还是头一次见，我可以远程给你看看。

**Comment by shihaoZheng** [comment]
![image](https://github.com/user-attachments/assets/eaf978c7-2c83-4c2c-bb43-08bbf0914272)
太奇怪了，大佬有空就直接连吧

**Comment by shihaoZheng** [comment]
解决啦，mihomo Alpha 版内核才支持新的dns.fake-ip-filter 规则集格式，目前分享篇下载的内核比较旧，目前只能等正式版内核的更新或者先手动安装Alpha 版内核尝鲜，谢谢热心肠大佬的在线支持！
