### ISSUE TITLE
更新内核后出现错误

### ISSUE THREAD

**Issue by popolife** [DustinWin/dustinwin.github.io#49]
![bugbug](https://github.com/user-attachments/assets/f0c665f9-cd60-4f15-840e-4c9e09a0bc6c)
启动服务后报错， @DustinWin 大佬看看啥情况

**Comment by DustinWin** [comment]
> > 提供更详细的信息，参考教程、所用核心等。
> 
> 分别参考了 分享篇：[分享 ShellCrash 搭载 sing-boxp 内核采用 ruleset 方案的一套配置] 及 [ShellCrash 搭载 sing-boxp 内核的配置-ruleset 方案]，都会出现以上截图的情况，更新了内核之后出现的，内核更新方式是参考大佬的工具篇里面首次导入的方式更新

使用 GitHub 源更新内核，不要用 JS 源。

**Comment by popolife** [comment]
> jsdelivr地址改成github.com地址，无法下载的话就套个反代。

![bug1](https://github.com/user-attachments/assets/cb036bd1-80c7-49d5-9bb5-f224482a9e32)
好像还是不行

**Comment by DustinWin** [comment]
> > jsdelivr地址改成github.com地址，无法下载的话就套个反代。
> 
> ![bug1](https://private-user-images.githubusercontent.com/165510731/362713924-cb036bd1-80c7-49d5-9bb5-f224482a9e32.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Mzk2MzYsIm5iZiI6MTcyNDkzOTMzNiwicGF0aCI6Ii8xNjU1MTA3MzEvMzYyNzEzOTI0LWNiMDM2YmQxLTgwYzctNDlkNS05YmI1LWYyMjQ0ODJhOWUzMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQxMzQ4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzkxMDdjZDM4ZGI5NDFhM2FlZWJiZGY3ZTA3OWFjMDQ3OGYyMDIzNTRkMTZkYWE3NWY4NTZjN2VjZjE0M2M1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aJh5FHc60W2O1ECy3-Uk0ObMf7lkEacWOYqgzZeQOzY) 好像还是不行

？？多谷歌。  
`curl -L https://mirror.ghproxy.com/https://github.com/DustinWin/clash_singbox-tools/releases/download/sing-box/sing-box-puernya-linux-armv8.tar.gz | tar -zx -C /tmp/ && crash`

**Comment by popolife** [comment]
> > > jsdelivr地址改成github.com地址，无法下载的话就套个反代。
> > 
> > 
> > ![错误1](https://private-user-images.githubusercontent.com/165510731/362713924-cb036bd1-80c7-49d5-9bb5-f224482a9e32.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Mzk2MzYsIm5iZiI6MTcyNDkzOTMzNiwicGF0aCI6Ii8xNjU1MTA3MzEvMzYyNzEzOTI0LWNiMDM2YmQxLTgwYzctNDlkNS05YmI1LWYyMjQ0ODJhOWUzMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQxMzQ4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzkxMDdjZDM4ZGI5NDFhM2FlZWJiZGY3ZTA3OWFjMDQ3OGYyMDIzNTRkMTZkYWE3NWY4NTZjN2VjZjE0M2M1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aJh5FHc60W2O1ECy3-Uk0ObMf7lkEacWOYqgzZeQOzY)好像还是不行
> 
> ？？多谷歌。 `curl -L https://mirror.ghproxy.com/https://github.com/DustinWin/clash_singbox-tools/releases/download/sing-box/sing-box-puernya-linux-armv8.tar.gz | tar -zx -C /tmp/ && crash`

对不起哈哈，已经解决问题了，感谢！
