### ISSUE TITLE
开启TUN模式后无法访问互联网

### ISSUE THREAD

**Issue by szz34** [DustinWin/dustinwin.github.io#50]
按照您发的clash verge的ruleset配置下来的，但是打开tun模式后电脑会断网，国内和国外网站都不能访问。
关闭tun后国内网站正常，打开系统代理后国外网站正常。
网络环境：校园网
请大佬帮忙看看。

clash verge仓库issue也有人反映该问题：
https://github.com/clash-verge-rev/clash-verge-rev/issues/1490

![image](https://github.com/user-attachments/assets/5f336147-38c7-4880-9e57-99d14d16e577)

**Comment by szz34** [comment]
自己摸索着解决了。
之前使用的事mihomo内核，而不是alpha版。
切换到alpha版之后，按照大佬分享的一套配置（https://proxy-tutorials.dustinwin.top/posts/share-clashverge-mihomo-ruleset/）又自己配了一下，打开tun后可以正常访问国内外网站了。
但是发现访问速度很慢，分析应该是DNS问题，按照另一教程（https://luyipao.top/2022/09/clashtun/）的方法，先查询了本校园网的默认DNS是223.6.6.6，把它添加到了“全局扩展配置”的DNS设置里，又在下面另外加了个谷歌的8.8.8.8，保存，正常起来了。

**Comment by XstormLeigh** [comment]
我跟你情况一样，但是弄了也是白弄，还是一个效果

**Comment by ykculnu** [comment]
哥啊，你最后解决了吗，我整几天了，方法基本试了个遍还是和你一样没有效果

**Comment by szz34** [comment]
> 我跟你情况一样，但是弄了也是白弄，还是一个效果

正常一段时间后又出问题了，后来我就没再用过tun模式了

**Comment by szz34** [comment]
> 哥啊，你最后解决了吗，我整几天了，方法基本试了个遍还是和你一样没有效果

还是没能解决，后来我就不用tun模式了，懒得折腾

**Comment by DustinWin** [comment]
建议跑个裸核试试 https://proxy-tutorials.dustinwin.top/posts/share-windows-mihomo-ruleset/

**Comment by XstormLeigh** [comment]
> 哥啊，你最后解决了吗，我整几天了，方法基本试了个遍还是和你一样没有效果

我现在在用clash verge 2.2.2, TUN能用，但是吧，也是抽风那种，有时候开机得等会儿，开开关关折腾一圈儿，我也不知道我的电脑到底是咋回事儿了。
