### ISSUE TITLE
大佬, 请教下 sing-box P 核的 fallback_rules

### ISSUE THREAD

**Issue by jqtmviyu** [DustinWin/dustinwin.github.io#51]
```
{
    "fallback_rules": [
      { "rule_set": ["cnip"], "server": "dns_direct" },
      { "match_all": true, "server": "dns_fakeip", "rewrite_ttl": 1 }
    ],
    "server": "dns_proxy"
  }
```

这里的 dns_proxy 是用来在里面rule_set cnip 的时候判断的吗?

第一层的 server 和 fallback_rules 里的server分别是什么作用?

尝试看p核的文档, 太简洁了看不懂😭

**Comment by DustinWin** [comment]
`"server": "dns_proxy"` 用于判断未知域名（不在你配置的规则内的域名）是否在国内。

**Comment by jqtmviyu** [comment]
> `"server": "dns_proxy"` 用于判断未知域名（不在你配置的规则内的域名）是否在国内。

请问是不是可以理解为:  
1. 先用 dns_proxy 解析不在规则的的域名为ip
2. 匹配 fallback里的第一条rule, 如果为 cnip, 则用 dns direct 再查询, 返回  dns direct 的结果
3. 如果不符合 第一条rule, 再全部返回fakeip, 当客户端请求fackeip的时候, 替换为 fackeip对应的域名, 由 远程代理 解析.

**Comment by DustinWin** [comment]
> > `"server": "dns_proxy"` 用于判断未知域名（不在你配置的规则内的域名）是否在国内。
> 
> 请问是不是可以理解为:
> 
> 1. 先用 dns_proxy 解析不在规则的的域名为ip
> 2. 匹配 fallback里的第一条rule, 如果为 cnip, 则用 dns direct 再查询, 返回  dns direct 的结果
> 3. 如果不符合 第一条rule, 再全部返回fakeip, 当客户端请求fackeip的时候, 替换为 fackeip对应的域名, 由 远程代理 解析.

就是这样。
