### ISSUE TITLE
curl无法下载 lemoeo/AX6S@main/auto_ssh.sh

### ISSUE THREAD

**Issue by dutry** [DustinWin/dustinwin.github.io#53]
参考[教程](https://proxy-tutorials.dustinwin.top/posts/pin-shellcrashadguardhome-singbox/#2-%E8%BF%9E%E6%8E%A5-telnet)

一直没有速度，报错：`curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to cdn.jsdelivr.net:443`

电脑上翻过墙之后可以正常下载

**Comment by DustinWin** [comment]
把 `cdn.jsdelivr.net` 改成 `fastly.jsdelivr.net` 试试。

**Comment by dutry** [comment]
问题解决了！

**Comment by DustinWin** [comment]
其实有说明，https://github.com/DustinWin/dustinwin.github.io?tab=readme-ov-file#%E5%AF%B9%E4%B8%8B%E8%BD%BD%E6%BA%90%E7%9A%84%E8%AF%B4%E6%98%8E
